services:

  backend:
    build:
      context: ./backend
    container_name: ets_backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: ets_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: